# Generated by Django 5.0.3 on 2024-06-06 17:50

import Ecommerce.Product.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Brand name", max_length=64, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=64, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Product.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=256)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Product slug", max_length=256, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Product description", max_length=1024),
                ),
                (
                    "is_digital",
                    models.BooleanField(
                        default=False, help_text="is the product digital ?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="is the product active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product brand",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Product.brand",
                    ),
                ),
                (
                    "category",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Product category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Product.category",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Product price", max_digits=10
                    ),
                ),
                ("sku", models.CharField(help_text="Product SKU", max_length=128)),
                (
                    "stock_qty",
                    models.IntegerField(help_text="Product quantity in stock"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="is the product active"
                    ),
                ),
                (
                    "order",
                    Ecommerce.Product.fields.OrderField(
                        blank=True, help_text="product line order"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Related product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_line",
                        to="Product.product",
                    ),
                ),
            ],
        ),
    ]
