# Generated by Django 5.0.3 on 2024-03-19 00:57

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="is_igital",
            new_name="is_digital",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="Product category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Product.category",
            ),
        ),
    ]
