# Generated by Django 5.0.3 on 2024-03-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name", max_length=64, unique=True
            ),
        ),
    ]
