# Generated by Django 5.0.3 on 2024-03-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=False, help_text="is the product active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_digital",
            field=models.BooleanField(
                default=False, help_text="is the product digital ?"
            ),
        ),
        migrations.CreateModel(
            name="ProductLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Product price", max_digits=10
                    ),
                ),
                ("sku", models.CharField(help_text="Product SKU", max_length=128)),
                (
                    "stock_qty",
                    models.IntegerField(help_text="Product quantity in stock"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="is the product active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Related product",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.product",
                    ),
                ),
            ],
        ),
    ]
