# Generated by Django 5.0.3 on 2024-03-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0004_product_is_active_alter_product_is_digital_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.SlugField(
                help_text="Product slug", max_length=256, unique=True
            ),
        ),
    ]
