# Generated by Django 5.0.3 on 2024-03-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Product", "0005_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                default="wake-up-call",
                help_text="Product slug",
                max_length=256,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Product name", max_length=256),
        ),
    ]
